# topaz.yaml
#
# Crowdin configuration file for AOSPA
#
# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017-2020 The LineageOS Project
# Copyright (C) 2023 Paranoid Android
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"api_token_env": AOSPA_CROWDIN_API_KEY
"base_path_env": AOSPA_CROWDIN_BASE_PATH
"project_id": 37349
"preserve_hierarchy": true

"files": [
  {
    "source":      '/frameworks/base/core/res/res/values/aospa_strings.xml'
    "translation": '/vendor/aospa/overlay/translations/AOSPAFrameworksTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/Paranoid/SystemUI/res/values/aospa_strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidSystemUITranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/ParanoidDoze/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidDozeTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/ParanoidGlyph/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidGlyphTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/ParanoidHub/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidHubTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/Launcher3/res/values/aospa_strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidLauncherTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/ParanoidPapers/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidPapersTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/ParanoidSense/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidSenseTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/packages/apps/Settings/res/values/aospa_strings.xml'
    "translation": '/vendor/aospa/overlay/translations/AOSPASettingsTranslation/res-%android_code%/%original_file_name%'
  },
  {
    "source":      '/vendor/aospa/apps/ParanoidThemePicker/res/values/strings.xml'
    "translation": '/vendor/aospa/overlay/translations/ParanoidThemePickerTranslation/res-%android_code%/%original_file_name%'
  }
]
